application: seleicao
version: 1

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  expiration: "365d"

- url: /static
  static_dir: static
  expiration: "365d"

- url: /assets
  static_dir: static
  expiration: "365d"

- url: /.*
  script: urls.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"


inbound_services:
- warmup

builtins:
- appstats: on
- deferred: on